language: php
php:
    - 5.5
    - 5.6
    - 7
install:
    - composer install
script:
    - phpunit --debug --verbose
notifications:
    email: false
    slack:
        secure: dlQeLKmk6qDwndXN8/0J8Ir6SiLJgap8L8HvJm7JyFQL32qsiJKstJzy4aVf7z64Or3PPI1bT8lI3JnJy+GztEfEiNXXwBCYiRBfU2JnkQaA6xkgOTyhlkK4Eis80P+3ajvuptnGj/CcU8FfwxR9CwxRASwEvgC6GQPwBcgU3vNjRec8Gm/g/1vrl2hMulW3oHjCxAUavIc/awnsUO+pO7yN7avjOycd0phwHLX6m/n6os97QyOak5TqkWOyItkZiTfw9qzHmz7VgLHMsE63Q6pMN1H1mauncuo06NxAiBeHhp1FUGpTUeD5nHPjF8I+NlUzM3wME8i2o+wp7nleWdCoN/+oGpa9rld5jj+S6yJtXM+Di7JH8WMLVhMoXJ76TgUHsYZ5Zy5ZcIZyx+xvhNfRSpODhNcCVd794km1X6+hmuX17Hp7/NrHksCsskdeg9FMkXPoti49dO01tteE82j9ynlme3SuYlD+/J5KPaV2hOw3VylE0EuWiXphMR7+WArIY2i5TEEVxBQdLWHT/SAhqBj/RknTonfDa+5y3o4CxphOq6Hvywsj2WonPJ1vPwX0bltsthqhQdJeu3Rs/hBXMau1UgzHSIljG3hSxOyDuVnbVRXYLxxSokIh/9SgZ9kaSyqY8U2ToFj6gLYhkPrC+UxMWXIUvT/9lkOjZhc=
